-- Generated by nwg-displays on 2026-09-01 at 13:33:51. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2560x1600@60.03",
    position = "5300x1200",
    scale = 2.0
})
hl.monitor({
    output = "DP-5",
    mode = "1920x1200@59.95",
    position = "3013x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-6",
    mode = "2560x1440@59.95",
    position = "4933x0",
    scale = 1.2000000000000002
})
