# Application bindings
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

# Unbind fullscreen from SUPER+F
unbind = SUPER, F

bindd = SUPER, RETURN, Terminal, exec, $termninal --working-directory="$(omarchy-cmd-terminal-cwd)" zsh
bindd = SUPER, F, Terminal, exec, $terminal zsh -c "yazi"
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPAC Omarchy menu, exec, omarchy-menu
bindd = SUPER, L, Lock, exec, hyprlock
bindd = SUPER, period, Symbols, exec, walker --provider symbols


